name: Deploy to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN }}

on:
  push:
    branches:
      - SP3_deploy_backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Echo values"
        run: |
          echo $VERCEL_PROJECT_ID
          echo $VERCEL_TOKEN

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          cd ./server
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} -y
